// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AdminPanel.DataModel.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AdminPanel.DataModel.Context
{
    public partial interface IOrderflowContextProcedures
    {
        Task<List<InsertSeedDataResult>> InsertSeedDataAsync(long? companyId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_SyncAPICustomersAsync(long? companyID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_SyncAPIProductsResult>> sp_SyncAPIProductsAsync(long? companyID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
