// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Address
{
    public long Id { get; set; }

    public byte AddressTypeId { get; set; }

    public int CountryId { get; set; }

    public int StateId { get; set; }

    public string ContactPerson { get; set; }

    public string Email { get; set; }

    public string County { get; set; }

    public int? CityId { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string PostalCode { get; set; }

    public string PhoneNumber { get; set; }

    public string StateName { get; set; }

    public string CityName { get; set; }

    public string CountryName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? CreatedBy { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual AddressType AddressType { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual State State { get; set; }

    public virtual ICollection<TempCart> TempCarts { get; set; } = new List<TempCart>();

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}