// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Comment
{
    public long Id { get; set; }

    public byte TypeId { get; set; }

    public long? CustomerId { get; set; }

    public long? UserId { get; set; }

    public string CommentDescription { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<TempCartItem> TempCartItems { get; set; } = new List<TempCartItem>();

    public virtual ICollection<TempCart> TempCarts { get; set; } = new List<TempCart>();

    public virtual CommentType Type { get; set; }
}