// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class CompanyInformationalText
{
    public long CompanyId { get; set; }

    public string TermsConditions { get; set; }

    public string NoticeBoard { get; set; }

    public string LiquorControl { get; set; }

    public string NonFood { get; set; }

    public string InvoiceFooter { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }
}