// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Company
{
    public long CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public bool? IsEmailMarketing { get; set; }

    public bool? IsMobileOrdering { get; set; }

    public bool? IsProofOfDelivery { get; set; }

    public bool? IsWebOrdering { get; set; }

    public bool? IsActie { get; set; }

    public string Logo { get; set; }

    public string DomainName { get; set; }

    public int? TimeZoneId { get; set; }

    public string CurrencyInfo { get; set; }

    public string PrimaryColor { get; set; }

    public string SecondaryColor { get; set; }

    public int? NextInvoiceNumber { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual CompanyConfigurationSetting CompanyConfigurationSetting { get; set; }

    public virtual ICollection<CompanyDataImportMapping> CompanyDataImportMappings { get; set; } = new List<CompanyDataImportMapping>();

    public virtual CompanyInformationalText CompanyInformationalText { get; set; }

    public virtual CompanyPackageDetail CompanyPackageDetail { get; set; }

    public virtual ICollection<CompanyPostedLink> CompanyPostedLinks { get; set; } = new List<CompanyPostedLink>();

    public virtual ICollection<CompanySlider> CompanySliders { get; set; } = new List<CompanySlider>();

    public virtual ICollection<CompanySpecial> CompanySpecials { get; set; } = new List<CompanySpecial>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DeliveryDateCutoff> DeliveryDateCutoffs { get; set; } = new List<DeliveryDateCutoff>();

    public virtual ICollection<DeliveryRun> DeliveryRuns { get; set; } = new List<DeliveryRun>();

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Filter> Filters { get; set; } = new List<Filter>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<MainCategory> MainCategories { get; set; } = new List<MainCategory>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<ProductAttribute> ProductAttributes { get; set; } = new List<ProductAttribute>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<SpecialPricing> SpecialPricings { get; set; } = new List<SpecialPricing>();

    public virtual ICollection<TargetMarketing> TargetMarketings { get; set; } = new List<TargetMarketing>();

    public virtual ICollection<TempCart> TempCarts { get; set; } = new List<TempCart>();

    public virtual GlobalTimeZone TimeZone { get; set; }

    public virtual ICollection<UnitOfMeasurement> UnitOfMeasurements { get; set; } = new List<UnitOfMeasurement>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}