// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Customer
{
    public long CustomerId { get; set; }

    public long CompanyId { get; set; }

    public string AlphaCode { get; set; }

    public string RegistrationNo { get; set; }

    public string CustomerName { get; set; }

    public string ContactName { get; set; }

    public string Email { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public string SalesmanCode { get; set; }

    public bool? IsDebtorOnHold { get; set; }

    public double? CreditLimit { get; set; }

    public bool? IsSuspended { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsSalesRep { get; set; }

    public bool? IsSpecialCategory { get; set; }

    public bool? IsParent { get; set; }

    public string PriceCode { get; set; }

    public double? BalanceTotal { get; set; }

    public double? Day30Balance { get; set; }

    public double? Day60Balance { get; set; }

    public double? Day90PlusBalance { get; set; }

    public double? Day120PlusBalance { get; set; }

    public double? TotalAmountDue { get; set; }

    public double? TotalAmountOwed { get; set; }

    public double? Ytdsales { get; set; }

    public double? Mtdsales { get; set; }

    public double? PreviousMonthSales { get; set; }

    public string StandardDeliveryDays { get; set; }

    public string PriceLevel { get; set; }

    public bool? HasSpecialPermittedDays { get; set; }

    public string PermittedDays { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Company Company { get; set; }

    public virtual ICollection<FavoriteList> FavoriteLists { get; set; } = new List<FavoriteList>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<SpecialPricing> SpecialPricings { get; set; } = new List<SpecialPricing>();

    public virtual ICollection<TargetMarketing> TargetMarketings { get; set; } = new List<TargetMarketing>();

    public virtual ICollection<TempCart> TempCarts { get; set; } = new List<TempCart>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<MainCategory> Categories { get; set; } = new List<MainCategory>();

    public virtual ICollection<Customer> ChildCustomers { get; set; } = new List<Customer>();

    public virtual ICollection<DeliveryRun> DeliveryRuns { get; set; } = new List<DeliveryRun>();

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Customer> ParentCustomers { get; set; } = new List<Customer>();

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}