// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class CustomerImport
{
    public long Id { get; set; }

    public double? CompanyId { get; set; }

    public string AlphaCode { get; set; }

    public string CustomerName { get; set; }

    public string ContactName { get; set; }

    public string Email { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public double? SalesmanCode { get; set; }

    public double? IsDebtorOnHold { get; set; }

    public string CreditLimit { get; set; }

    public string IsSuspended { get; set; }

    public double? IsActive { get; set; }

    public double? IsSalesRep { get; set; }

    public string IsSpecialCategory { get; set; }

    public string PriceCode { get; set; }

    public string BalanceTotal { get; set; }

    public string Day30Balance { get; set; }

    public string Day60Balance { get; set; }

    public string Day90PlusBalance { get; set; }

    public string Day120PlusBalance { get; set; }

    public string TotalAmountDue { get; set; }

    public string TotalAmountOwed { get; set; }

    public string Ytdsales { get; set; }

    public string Mtdsales { get; set; }

    public string PreviousMonthSales { get; set; }

    public string StandardDeliveryDays { get; set; }

    public string PriceLevel { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public DateTime? CreatedOn { get; set; }
}