// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class DeliveryDateCutoff
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public bool? IsCutoffEnabled { get; set; }

    public TimeSpan? CutoffTime { get; set; }

    public DateTime? CutoffDate { get; set; }

    public bool? IsSameDayDelivery { get; set; }

    public bool? IsLimitDatesTo1Month { get; set; }

    public bool? AdvancedCutoffRules { get; set; }

    public byte? CutoffTypeId { get; set; }

    public int? DailyOrderLimit { get; set; }

    public string PermittedDeliveryDays { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }

    public virtual DeliveryCutoffType CutoffType { get; set; }
}