// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class DeliveryCutoffType
{
    public byte Id { get; set; }

    public string TypeDesc { get; set; }

    public virtual ICollection<DeliveryDateCutoff> DeliveryDateCutoffs { get; set; } = new List<DeliveryDateCutoff>();
}