// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Discount
{
    public int Id { get; set; }

    public long CompanyId { get; set; }

    public byte TypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CouponCode { get; set; }

    public bool? UsePercentage { get; set; }

    public double? DiscountPercentage { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? MaxDiscountAmount { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? MinCartValue { get; set; }

    public bool? RequiresCouponCode { get; set; }

    public byte? LimitationTypeId { get; set; }

    public byte? LimitationTimes { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }

    public virtual DiscountLimitationType LimitationType { get; set; }

    public virtual DiscountType Type { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}