// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class FavoriteListType
{
    public byte Id { get; set; }

    public string Description { get; set; }

    public virtual ICollection<FavoriteList> FavoriteLists { get; set; } = new List<FavoriteList>();
}