// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class FavoriteList
{
    public long Id { get; set; }

    public byte TypeId { get; set; }

    public long CustomerId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public bool? IsSalesRepList { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<FavoriteListItem> FavoriteListItems { get; set; } = new List<FavoriteListItem>();

    public virtual FavoriteListType Type { get; set; }
}