// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Filter
{
    public int FilterId { get; set; }

    public long CompanyId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}