// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class GlobalTimeZone
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Offset { get; set; }

    public string DaylightName { get; set; }

    public DateTime? DaylightStart { get; set; }

    public DateTime? DaylightEnd { get; set; }

    public double? Delta { get; set; }

    public string Zid { get; set; }

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();
}