// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Group
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public byte GroupTypeId { get; set; }

    public byte GroupScopeId { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<GroupDetail> GroupDetails { get; set; } = new List<GroupDetail>();

    public virtual GroupScope GroupScope { get; set; }

    public virtual GroupType GroupType { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<TargetMarketing> TargetMarketings { get; set; } = new List<TargetMarketing>();
}