// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class GroupDetail
{
    public long GroupId { get; set; }

    public long ReferenceId { get; set; }

    public virtual Group Group { get; set; }
}