// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class ImportLog
{
    public int Id { get; set; }

    public int MappingId { get; set; }

    public string ImportType { get; set; }

    public bool? IsSuccess { get; set; }

    public string Response { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual CompanyDataImportMapping Mapping { get; set; }
}