// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class MessageRecipient
{
    public long MessageId { get; set; }

    public long UserId { get; set; }

    public bool IsRead { get; set; }

    public virtual Message Message { get; set; }

    public virtual User User { get; set; }
}