// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public int? OrderNumber { get; set; }

    public long CompanyId { get; set; }

    public long CustomerId { get; set; }

    public long UserId { get; set; }

    public long? AddressId { get; set; }

    public long? CommentId { get; set; }

    public long? DeliveryRunId { get; set; }

    public byte StatusId { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string PoNumber { get; set; }

    public decimal? TotalWithTax { get; set; }

    public decimal? TotalWithoutTax { get; set; }

    public int? DiscountId { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal OrderTotal { get; set; }

    public string ErpOrderNo { get; set; }

    public string ErpReference { get; set; }

    public string ErpInvoiceNo { get; set; }

    public bool? HasFreightCharges { get; set; }

    public bool? HasNonDeliveryDayCharges { get; set; }

    public decimal? FreightCharge { get; set; }

    public decimal? NonDeliveryDayCharge { get; set; }

    public bool? IsAutoOrdered { get; set; }

    public bool? IsCancled { get; set; }

    public bool? IsPostedToErp { get; set; }

    public string DeviceType { get; set; }

    public string DeviceToken { get; set; }

    public string AppVersion { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string OrderNote { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Address Address { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Company Company { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DeliveryRun DeliveryRun { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}