// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class OrderItem
{
    public long OrderItemId { get; set; }

    public long OrderId { get; set; }

    public long ProductId { get; set; }

    public long? CommentId { get; set; }

    public double Quantity { get; set; }

    public double? BackOrderQuantity { get; set; }

    public decimal Price { get; set; }

    public decimal? Cost { get; set; }

    public long UnitId { get; set; }

    public bool? IsGst { get; set; }

    public double? TaxRate { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal? AttributePriceAdjustment { get; set; }

    public decimal? PriceInclTax { get; set; }

    public decimal? TotalWithoutTax { get; set; }

    public decimal TotalPrice { get; set; }

    public bool? IsPantry { get; set; }

    public bool? IsDonationItem { get; set; }

    public string AttributeMappingJson { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual UnitOfMeasurement Unit { get; set; }

    public virtual ICollection<ProductAttributeValue> AttributeValues { get; set; } = new List<ProductAttributeValue>();
}