// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class Package
{
    public int PackageId { get; set; }

    public string Description { get; set; }

    public byte IntervalId { get; set; }

    public decimal Price { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsMobileOrdering { get; set; }

    public bool? IsProofOfDelivery { get; set; }

    public bool? IsWebOrdering { get; set; }

    public int? OrderLimit { get; set; }

    public int? CustomerLimit { get; set; }

    public int? ProductLimit { get; set; }

    public int? TrialPeriodDays { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual ICollection<CompanyPackageDetail> CompanyPackageDetails { get; set; } = new List<CompanyPackageDetail>();

    public virtual PackageInterval Interval { get; set; }

    public virtual PackageFeature PackageFeature { get; set; }
}