// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class PaymentTransaction
{
    public int Id { get; set; }

    public byte? TypeId { get; set; }

    public long CompanyId { get; set; }

    public decimal Amount { get; set; }

    public bool IsSubscription { get; set; }

    public string SubscriptionId { get; set; }

    public byte StatusId { get; set; }

    public string ConfirmationId { get; set; }

    public string JsonResponse { get; set; }

    public long? ModifiedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual Company Company { get; set; }

    public virtual Status Status { get; set; }

    public virtual PaymentProcessor Type { get; set; }
}