// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class PredefinedProductAttributeValue
{
    public int Id { get; set; }

    public int AttributeId { get; set; }

    public string Name { get; set; }

    public decimal? PriceAdjustment { get; set; }

    public bool? UsePercentage { get; set; }

    public decimal? WeightAdjustment { get; set; }

    public bool? IsPreSelected { get; set; }

    public int? DisplayOrder { get; set; }

    public decimal? Cost { get; set; }

    public virtual ProductAttribute Attribute { get; set; }
}