// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class ProductInventory
{
    public long Id { get; set; }

    public long ProductId { get; set; }

    public int WarehouseId { get; set; }

    public long? UnitId { get; set; }

    public double? StockQuantity { get; set; }

    public double? QuantityOnOrder { get; set; }

    public DateTime? OrderExpectedDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual UnitOfMeasurement Unit { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}