// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class ProductImport
{
    public long Id { get; set; }

    public double? CompanyId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string ShortDescription { get; set; }

    public string CategoryName { get; set; }

    public string MainCategoryName { get; set; }

    public string FilterName { get; set; }

    public double? Price { get; set; }

    public double? CostPrice { get; set; }

    public double? Price1 { get; set; }

    public double? Price2 { get; set; }

    public double? Price3 { get; set; }

    public double? Price4 { get; set; }

    public string Price5 { get; set; }

    public string Barcode { get; set; }

    public string BrandName { get; set; }

    public string SupplierName { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsAvailable { get; set; }

    public bool? IsRewardItem { get; set; }

    public bool? IsCore { get; set; }

    public bool? IsGst { get; set; }

    public string IsBuyIn { get; set; }

    public string IsNew { get; set; }

    public string IsOnSale { get; set; }

    public string IsBackSoon { get; set; }

    public string IsSellBelowCost { get; set; }

    public string IsDonationItem { get; set; }

    public string StandardCost { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    public string CustomField5 { get; set; }

    public string CustomField6 { get; set; }

    public string CustomField7 { get; set; }

    public string CustomField8 { get; set; }

    public string CustomField9 { get; set; }

    public string CustomField10 { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Unit1 { get; set; }

    public double? QtyPerUnit1 { get; set; }

    public string Unit2 { get; set; }

    public double? QtyPerUnit2 { get; set; }

    public string Unit3 { get; set; }

    public double? QtyPerUnit3 { get; set; }
}