// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class ProductAttributeValue
{
    public int Id { get; set; }

    public int ProductMappingId { get; set; }

    public string Value { get; set; }

    public string ColorRgb { get; set; }

    public decimal? PriceAdjustment { get; set; }

    public bool? UsePercentage { get; set; }

    public decimal? WeightAdjustment { get; set; }

    public decimal? CostPrice { get; set; }

    public double? MinQuantity { get; set; }

    public bool? IsPreSelected { get; set; }

    public long? ImageId { get; set; }

    public byte? DisplayOrder { get; set; }

    public bool? IsActive { get; set; }

    public int? StockQuantity { get; set; }

    public virtual ProductAttributeMapping ProductMapping { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<TempCartItem> TempCartItems { get; set; } = new List<TempCartItem>();
}