// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class ProductAttributeMapping
{
    public int Id { get; set; }

    public long ProductId { get; set; }

    public int AttributeId { get; set; }

    public string Placeholder { get; set; }

    public bool? IsRequired { get; set; }

    public byte DisplayControlTypeId { get; set; }

    public byte? DisplayOrder { get; set; }

    public bool? IsActive { get; set; }

    public virtual ProductAttribute Attribute { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductAttributeValue> ProductAttributeValues { get; set; } = new List<ProductAttributeValue>();
}