// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class SpecialPriceImport
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public string CustomerName { get; set; }

    public string ProductCode { get; set; }

    public double? Price { get; set; }

    public string Unit { get; set; }

    public bool? IsLimitedPeriod { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsQuantitySpecific { get; set; }

    public double? MinQuantity { get; set; }

    public double? MaxQuantity { get; set; }

    public bool? IsUnitSpecific { get; set; }

    public bool? IsActive { get; set; }
}