// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class SubCategory
{
    public long Id { get; set; }

    public long MainCategoryId { get; set; }

    public string SubCategoryName { get; set; }

    public bool? IsActive { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual MainCategory MainCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}