// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class TargetMarketing
{
    public long Id { get; set; }

    public long CompanyId { get; set; }

    public long? GroupId { get; set; }

    public long? CustomerId { get; set; }

    public byte? MarketingTypeId { get; set; }

    public string Title { get; set; }

    public string FileName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public long? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public virtual Company Company { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Group Group { get; set; }

    public virtual MarketingType MarketingType { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}