// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class UnitOfMeasurement
{
    public long UnitId { get; set; }

    public long CompanyId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public bool? IsActive { get; set; }

    public bool? AllowQtyInDecimal { get; set; }

    public long? CreatedBy { get; set; }

    public long? ModifiedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductInventory> ProductInventories { get; set; } = new List<ProductInventory>();

    public virtual ICollection<ProductUnit> ProductUnits { get; set; } = new List<ProductUnit>();

    public virtual ICollection<SpecialPricing> SpecialPricings { get; set; } = new List<SpecialPricing>();

    public virtual ICollection<TempCartItem> TempCartItems { get; set; } = new List<TempCartItem>();
}