// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class UserPassword
{
    public long Id { get; set; }

    public long? UserId { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual User User { get; set; }
}