// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPanel.DataModel.Models;

public partial class UserDeviceLocationAndToken
{
    public long Id { get; set; }

    public long? UserId { get; set; }

    public string DeviceType { get; set; }

    public string DeviceToken { get; set; }

    public string IpAddress { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public DateTime? LastLogin { get; set; }

    public virtual User User { get; set; }
}